/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSalesBiDashboardRouteImport } from './routes/projects/sales-bi-dashboard'
import { Route as ProjectsRecruitmentAppRouteImport } from './routes/projects/recruitment-app'
import { Route as ProjectsFoodDeliveryRouteImport } from './routes/projects/food-delivery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSalesBiDashboardRoute =
  ProjectsSalesBiDashboardRouteImport.update({
    id: '/projects/sales-bi-dashboard',
    path: '/projects/sales-bi-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsRecruitmentAppRoute = ProjectsRecruitmentAppRouteImport.update({
  id: '/projects/recruitment-app',
  path: '/projects/recruitment-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFoodDeliveryRoute = ProjectsFoodDeliveryRouteImport.update({
  id: '/projects/food-delivery',
  path: '/projects/food-delivery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/food-delivery': typeof ProjectsFoodDeliveryRoute
  '/projects/recruitment-app': typeof ProjectsRecruitmentAppRoute
  '/projects/sales-bi-dashboard': typeof ProjectsSalesBiDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/food-delivery': typeof ProjectsFoodDeliveryRoute
  '/projects/recruitment-app': typeof ProjectsRecruitmentAppRoute
  '/projects/sales-bi-dashboard': typeof ProjectsSalesBiDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/food-delivery': typeof ProjectsFoodDeliveryRoute
  '/projects/recruitment-app': typeof ProjectsRecruitmentAppRoute
  '/projects/sales-bi-dashboard': typeof ProjectsSalesBiDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/food-delivery'
    | '/projects/recruitment-app'
    | '/projects/sales-bi-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/food-delivery'
    | '/projects/recruitment-app'
    | '/projects/sales-bi-dashboard'
  id:
    | '__root__'
    | '/'
    | '/projects/food-delivery'
    | '/projects/recruitment-app'
    | '/projects/sales-bi-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsFoodDeliveryRoute: typeof ProjectsFoodDeliveryRoute
  ProjectsRecruitmentAppRoute: typeof ProjectsRecruitmentAppRoute
  ProjectsSalesBiDashboardRoute: typeof ProjectsSalesBiDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sales-bi-dashboard': {
      id: '/projects/sales-bi-dashboard'
      path: '/projects/sales-bi-dashboard'
      fullPath: '/projects/sales-bi-dashboard'
      preLoaderRoute: typeof ProjectsSalesBiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/recruitment-app': {
      id: '/projects/recruitment-app'
      path: '/projects/recruitment-app'
      fullPath: '/projects/recruitment-app'
      preLoaderRoute: typeof ProjectsRecruitmentAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/food-delivery': {
      id: '/projects/food-delivery'
      path: '/projects/food-delivery'
      fullPath: '/projects/food-delivery'
      preLoaderRoute: typeof ProjectsFoodDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsFoodDeliveryRoute: ProjectsFoodDeliveryRoute,
  ProjectsRecruitmentAppRoute: ProjectsRecruitmentAppRoute,
  ProjectsSalesBiDashboardRoute: ProjectsSalesBiDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
